### ISSUE TITLE
bug: after unlocking on iOS does not return to mode, which is relevant for the actual orientation of the device

### ISSUE THREAD

**Issue by Brullworfel** [robingenz/capacitor-screen-orientation#13]
**Plugin version:**
1.1.2

Capacitor 3.3.2
Ionic-Angular 5.9.3

**Platform(s):**
iOS

**Current behavior:**
On Android: The screen locks in landscape orientation, then, after unlocking, returns to portrait mode, which is relevant for the actual orientation of the device. Please look video here: https://youtu.be/RjBMZq-t48U

But on iOS, after unlocking, screen does not return to the mode that is relevant for the actual orientation of the device. Please look video here: https://youtu.be/nEbDn-zd3zA

**Expected behavior:**
When unlocking, screen orientation must return to the mode that is relevant for the actual orientation of the device.

**Steps to reproduce:**

1. Keep your iPhone upright at all steps;
2. Lock screen orientation to Landscape mode:

`ScreenOrientation.lock({ type: OrientationType.LANDSCAPE })`

3. Unlock screen orientation:

`ScreenOrientation.unlock();`

**Capacitor doctor:**
```
Latest Dependencies:

  @capacitor/cli: 3.3.4
  @capacitor/core: 3.3.4
  @capacitor/android: 3.3.4
  @capacitor/ios: 3.3.4

Installed Dependencies:

  @capacitor/ios: 3.3.4
  @capacitor/cli: 3.3.4
  @capacitor/core: 3.3.4
  @capacitor/android: 3.3.4

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

**Comment by robingenz** [comment]
Hi @Brullworfel,
thank you for this detailed request and filling out the issue template.
I remember you had reported this before (see https://github.com/robingenz/capacitor-screen-orientation/issues/6#issuecomment-881602149).
I'm going to take another look at that. Maybe this time I will find a fix.
It is definitely my goal that the plugin behaves the same on all platforms.

**Comment by Brullworfel** [comment]
Thank you @robingenz !

Maybe it helps you: https://developer.apple.com/documentation/uikit/uiviewcontroller/1621400-attemptrotationtodeviceorientati

**Comment by robingenz** [comment]
Great hint! I'll try that. Thank you!

**Comment by robingenz** [comment]
@Brullworfel Can you give it a try?

```
npm i @robingenz/capacitor-screen-orientation@1.1.2-dev.a1e395e.1641942951
```

**Comment by Brullworfel** [comment]
@robingenz Sure! I will report on the test today, thank you!

**Comment by Brullworfel** [comment]
@robingenz This works perfectly! Thank you!

**Comment by robingenz** [comment]
@Brullworfel Great!
