### ISSUE TITLE
bug: wrong event emit when lock

### ISSUE THREAD

**Issue by riderx** [robingenz/capacitor-screen-orientation#15]
**Plugin version:**
1.1.4

**Platform(s):**
ios

**Current behavior:**
when listen to screenOrientationChange and then lock in landscape, i receive portrait-primary

**Expected behavior:**
when locking, i should receive the orientation locked

**Steps to reproduce:**
use the code below in your app to see it happen

<img width="615" alt="Screenshot 2022-04-13 at 16 36 28" src="https://user-images.githubusercontent.com/4084527/163217395-7238bf34-18b8-45d6-86f0-b1e647974f8f.png">

**Related code:**
```
      ScreenOrientation.addListener('screenOrientationChange', async (res) => {
        const current = await ScreenOrientation.getCurrentOrientation()
        console.log('orientation', current, res)
      })
     ScreenOrientation.lock({ type: OrientationType.LANDSCAPE })
```

**Other information:**

**Capacitor doctor:**

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.4.3
  @capacitor/core: 3.4.3
  @capacitor/android: 3.4.3
  @capacitor/ios: 3.4.3

Installed Dependencies:

  @capacitor/core: 3.4.3
  @capacitor/android: 3.4.3
  @capacitor/cli: 3.4.3
  @capacitor/ios: 3.4.3

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

**Comment by robingenz** [comment]
I was able to reproduce it. I will publish a fix.

**Comment by riderx** [comment]
@robingenz your reactivity is wonderful!
We should create an GitHub org with the best contributor like you and do open collective to pay the best contributor.
That something needed in the ecosystem to me, now the community plugin is failing is job and make the tech look week by the lack of reactivity...
i understand it, it needs a real tangible incentive to me

**Comment by riderx** [comment]
@robingenz thanks for the fix i tried today and seems the listener send the good value but not the function who get .
<img width="636" alt="Screenshot 2022-04-14 at 13 22 10" src="https://user-images.githubusercontent.com/4084527/163389659-0087cc63-af24-49e6-b88b-a2baa89de900.png">
The codes who do this logging
```javascript
      ScreenOrientation.addListener('screenOrientationChange', async (res) => {
        const current = await ScreenOrientation.getCurrentOrientation()
        console.log('orientation', current, res)
      })
```

**Comment by robingenz** [comment]
> @robingenz your reactivity is wonderful! We should create an GitHub org with the best contributor like you and do open collective to pay the best contributor. That something needed in the ecosystem to me, now the community plugin is failing is job and make the tech look week by the lack of reactivity... i understand it, it needs a real tangible incentive to me

Thank you for your kind words. I'll have to think about that. I have never come up with this idea. 😄 

Okay, i will have a look again.

**Comment by robingenz** [comment]
@riderx You can give it a try: 
```
npm i @robingenz/capacitor-screen-orientation@1.1.5-dev.a2dfb78.1649947447
```

**Comment by riderx** [comment]
@robingenz i do it now !
What tool do you use to generate the version number ?

**Comment by riderx** [comment]
<img width="1310" alt="Screenshot 2022-04-14 at 16 03 16" src="https://user-images.githubusercontent.com/4084527/163418491-806a0567-a105-4900-b303-4a07e17192e6.png">
something is missing ^^

**Comment by riderx** [comment]
@robingenz oh ok thanks !
i will check then

**Comment by riderx** [comment]
@robingenz still getting the issue :/ 
at least i was able to release with the result of the listener `screenOrientationChange` but that weird `getCurrentOrientation ` still return the wrong one

**Comment by robingenz** [comment]
Thanks for testing.
I will have my Mac back on Monday. Then I can test it myself and find a fix.

**Comment by robingenz** [comment]
Okay, i fixed and tested it:
```
npm i @robingenz/capacitor-screen-orientation@1.1.5-dev.698d97d.1650353439
```
Does it work as you expect?
