### ISSUE TITLE
bug: faecup and facedown in ios send portrait event

### ISSUE THREAD

**Issue by riderx** [robingenz/capacitor-screen-orientation#9]
**Plugin version:**
latest

**Platform(s):**
ios

**Current behavior:**
when listen to change horientation and phone is put horizontally on table from landscape mode, it should stay in landscape but instead the faceup event is fired .
And this is transformed to default event `portrait`

**Expected behavior:**
No event should be fired when `faceup` `facedown` or optionally

**Steps to reproduce:**
Add this code to one app, and then move the phone into landscape and put it horizontally on table. you will see `portrait-primary` in the logs
```
      ScreenOrientation.addListener('screenOrientationChange', async () => {
        console.log(await ScreenOrientation.getCurrentOrientation())
      })
```

**Related code:**
The issue come from this line https://github.com/robingenz/capacitor-screen-orientation/blob/a5d08ea371ca14523a56949d7cf3fcdc4d3829e7/ios/Plugin/ScreenOrientation.swift#L89

**Other information:**
here is the Apple doc

**Comment by riderx** [comment]
I can propose a fix tomorow

**Comment by robingenz** [comment]
Hi @riderx,
Thank you for your interest in this plugin. I will have a look at it after work.

**Comment by robingenz** [comment]
I have created a fix.
You can give it a try: 
```
@robingenz/capacitor-screen-orientation@1.1.0-dev.09c2161.1639481757
```
I would be happy to receive feedback.

**Comment by riderx** [comment]
@robingenz super efficient ! i will check !

**Comment by riderx** [comment]
@robingenz it fix the issue !! perfect !
